version: "3.8"
services:
  paper-site-mongodb:
    image: mongo:latest
    container_name: paper-site-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongoData:/data/db
      - ./paper-site-mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=PsswrdPaper_5Kght4rgHAdmin
      - MONGO_INITDB_DATABASE=paperDev

  paper-site-nginx-proxy:
    build: ./paper-site-nginx
    container_name: paper-site-nginx-proxy
    ports:
      - "80:80"
      - "443:443"

  # paper-site-letsencrypt-proxy:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   container_name: paper-site-letsencrypt-proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - letsencrypt-certs:/etc/nginx/certs
  #     - letsencrypt-vhost-d:/etc/nginx/vhost.d
  #     - letsencrypt-html:/usr/share/nginx/html
  #   environment:
  #     - NGINX_PROXY_CONTAINER=paper-site-nginx-proxy

  paper-site-react:
    build: ./paper-site-react
    container_name: paper-site-react
    restart: always
    ports:
      - 8085:8085
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # env_file:
    #   - ./.env
    # environment:
    #   LETSENCRYPT_HOST: blog.ccnextgen.online
    #   VIRTUAL_HOST: blog.ccnextgen.online

  paper-site-nodejs:
    build: ./paper-site-nodejs
    container_name: paper-site-nodejs
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./paper-site-nodejs/logs:/home/node/app/logs
    depends_on:
      - paper-site-mongodb
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    # environment:
    #   LETSENCRYPT_HOST: blog.ccnextgen.online
    #   VIRTUAL_HOST: blog.ccnextgen.online
    #   VIRTUAL_PATH: /api
    #   LETSENCRYPT_PATH: /api
  
  

volumes:
  letsencrypt-certs:
  letsencrypt-vhost-d:
  letsencrypt-html:
